src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[UniqueEntity('name')]
#[ORM\Entity(repositoryClass: RecipeRepository::class)]
#[ORM\Table(name: 'recipes')]
#[ORM\HasLifecycleCallbacks]
class Recipe
{
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
        $this->ingredients = new ArrayCollection();
    }

    #[ORM\PreUpdate]
    public function setUpdatedAt(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 50)]
    #[Assert\NotBlank()]
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'The name must be at least {{ limit }} characters long',
        maxMessage: 'The name cannot be longer than {{ limit }} characters'
    )]
    private string $name;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    #[Assert\Positive(message: 'The time must be a positive number')]
    #[Assert\LessThanOrEqual(
        value: 1440,
        message: 'The time cannot be greater than {{ compared_value/60 }} hours'
    )]
    private ?int $time = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    #[Assert\Positive(message: 'The number of people must be a positive number')]
    #[Assert\LessThanOrEqual(
        value: 50,
        message: 'The number of people cannot be greater than {{ compared_value }}'
    )]
    private ?int $people = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    #[Assert\Positive(message: 'The difficulty must be a positive number')]
    #[Assert\LessThanOrEqual(
        value: 5,
        message: 'The difficulty cannot be greater than {{ compared_value }}'
    )]
    private ?int $difficulty = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    #[Assert\Length(
        min: 10,
        max: 1500,
        minMessage: 'The description must be at least {{ limit }} characters long',
        maxMessage: 'The description cannot be longer than {{ limit }} characters',
    )]
    private string $description;

    #[ORM\Column(type: Types::FLOAT, nullable: true)]
    #[Assert\Positive(message: 'The price must be a positive number')]
    #[Assert\LessThanOrEqual(
        value: 1000,
        message: 'The price cannot be greater than {{ compared_value }}'
    )]
    private ?float $price = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $isFavorite;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    #[Assert\NotNull(message: 'The createdAt date cannot be null')]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    #[Assert\NotNull(message: 'The updatedAt date cannot be null')]
    private \DateTimeImmutable $updatedAt;

    /**
     * @var Collection<int, Ingredient>
     */
    #[ORM\ManyToMany(targetEntity: Ingredient::class, inversedBy: 'recipes')]
    private Collection $ingredients;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getTime(): ?int
    {
        return $this->time;
    }

    public function setTime(?int $time): static
    {
        $this->time = $time;

        return $this;
    }

    public function getPeople(): ?int
    {
        return $this->people;
    }

    public function setPeople(?int $people): static
    {
        $this->people = $people;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function setDifficulty(?int $difficulty): static
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function isFavorite(): bool
    {
        return $this->isFavorite;
    }

    public function setIsFavorite(bool $isFavorite): static
    {
        $this->isFavorite = $isFavorite;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredient $ingredient): static
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients->add($ingredient);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): static
    {
        $this->ingredients->removeElement($ingredient);

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Ingredient;
use App\Entity\Recipe;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;


class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'class' => 'col-8',
                    'minlength' => '2',
                    'maxlength' => '50'
                ],
                'label' => 'Nom',
                'label_attr' => [
                    'class' => 'mt-4 col-4 text-start'
                ],
                'required'=>true,
                'constraints' => [
                    new Assert\Length(['min' => 2, 'max' => 50]),
                    new Assert\NotBlank()
                ]
            ])
            ->add('time',IntegerType::class,[
                'attr'=> [
                    'class'=>'col-8',
                    'min'=>1,
                    'max'=>1440
                ],
                'label'=>'Temps de préparation (minutes)',
                'label_attr'=>[
                    'class'=>'mt-4 text-start'
                ],
                'required'=>false,
                'constraints'=>[
                    new Assert\Positive(),
                    new Assert\LessThanOrEqual(['value'=>1440])
                ]
            ])
            ->add('people',IntegerType::class,[
                'attr'=> [
                    'class'=>'col-8',
                    'min'=>1,
                    'max'=>50
                ],
                'label'=>'Nombre de personnes',
                'label_attr'=>[
                    'class'=>'mt-4 col-4 text-start'
                ],
                'required'=>false,
                'constraints'=>[
                    new Assert\Positive(),
                    new Assert\LessThanOrEqual(['value'=>50])
                ]
            ])
            ->add('difficulty',RangeType::class,[
                'attr'=> [
                    'class'=>'col-8',
                    'min'=>1,
                    'max'=>5
                ],
                'label'=>'Difficulté /5',
                'label_attr'=>[
                    'class'=>'mt-4 col-4 text-start'
                ],
                'required'=>false,
                'constraints'=>[
                    new Assert\Positive(),
                    new Assert\LessThanOrEqual(['value'=>5])
                ]
            ])
            ->add('description',TextareaType::class,[
                'attr'=> [
                    'class'=>'col-8 mb-4',
                    'minlength'=>10,
                    'maxlength'=>1500
                ],
                'label'=>'Description',
                'label_attr'=>[
                    'class'=>'mt-4 col-4 text-start'
                ],
                'required'=>true,
                'constraints'=>[
                    new Assert\Length(['min'=>10,'max'=>1500]),
                    new Assert\NotBlank()
                ]
            ])
            ->add('isFavorite',CheckboxType::class,[
                'label'=>'Favoris',
                'required'=>false
            ])
            ->add('price',MoneyType::class,[
                'attr'=> [
                    'class'=>'col-8',
                    'min'=>1,
                    'max'=>1000
                ],
                'label'=>'Prix €',
                'currency'=>'',
                'label_attr'=>[
                    'class'=>'mt-4 text-start'
                ],
                'required'=>false,
                'constraints'=>[
                    new Assert\Positive(),
                    new Assert\LessThanOrEqual(['value'=>1000])
                ]
            ])
            ->add('ingredients', EntityType::class, [
                'class' => Ingredient::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Enregistrer',
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Form\RecipeType;
use App\Repository\RecipeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/recettes', name: 'recettes.')]
class RecipeController extends AbstractController
{
    /**
     * @Route('/', name: 'index', methods: ['GET'])
     * @param RecipeRepository $repository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    #[Route('', name: 'index', methods: ['GET'])]
    public function index(RecipeRepository $repository, PaginatorInterface $paginator, Request $request): Response
    {
        $recettes = $paginator->paginate(
            $repository->findAll(),
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('pages/recipe/index.html.twig', [
            'recettes' => $recettes
        ]);
    }

    /**
     * @Route('/show/{id}', name: 'show', methods: ['GET'])
     * @param RecipeRepository $repository
     * @param int $id
     * @return Response
     */
    #[Route('/{id}', name: 'show', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show(RecipeRepository $repository, int $id): Response
    {
        $recette = $repository->find($id);
        return $this->render('pages/recipe/show.html.twig', [
            'recette' => $recette
        ]);
    }

    /**
     * @Route('/create', name: 'create', methods: ['GET', 'POST'])
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('/create', name: 'create', methods: ['GET', 'POST'])]
    public function create(Request $request, EntityManagerInterface $manager): Response
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();
            $manager->persist($recipe);
            $manager->flush();
            $this->addFlash('success', "La recette a bien été ajoutée !");
            return $this->redirectToRoute('recettes.index');
        } elseif ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('danger', "Un problème est survenu lors de la création de la recette");
            return $this->redirectToRoute('recettes.index');
        }
        return $this->render('pages/recipe/create.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route('/edit/{id}', name: 'edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])
     * @param Recipe $recipe
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('/edit/{id}', name: 'edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function edit(Recipe $recipe, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();
            $manager->persist($recipe);
            $manager->flush();
            $this->addFlash('success', 'Votre recette a bien été modifiée !');
            return $this->redirectToRoute('recettes.index');
        } elseif ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('danger', 'Un problème est survenu lors de la modification de la recette.');
            return $this->redirectToRoute('recettes.index');
        }
        return $this->render('pages/recipe/edit.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route('/delete/{id}', name: 'delete', requirements: ['id' => "\d+"], methods: ['GET'])
     * @param Recipe $recipe
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('/delete/{id}', name: 'delete',requirements: ['id'=>"\d+"], methods: ['GET'])]
    public function delete(Recipe $recipe, EntityManagerInterface $manager): Response
    {
        $manager->remove($recipe);
        $manager->flush();
        $this->addFlash('success', 'La recette a bien été supprimée !');
        return $this->redirectToRoute('recettes.index');
    }

}

templates/pages/recipe/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cookable - Ajouter une Recette{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-4">Ajouter une Recette</h1>
        <div class="container mx-auto col-6">
            {{ form_start(form) }}
            <div class="form-group my-1">
                {{ form_label(form.name) }}
                {{ form_widget(form.name) }}
                <div class="form-error">{{ form_errors(form.name) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.time)}}
                {{ form_widget(form.time) }}
                <div class="form-error">{{ form_errors(form.time) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.people)}}
                {{ form_widget(form.people) }}
                <div class="form-error">{{ form_errors(form.people) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.difficulty) }}
                {{ form_widget(form.difficulty) }}
                <div class="form-error">{{ form_errors(form.difficulty) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.description) }}
                {{ form_widget(form.description) }}
                <div class="form-error">{{ form_errors(form.description) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_widget(form.isFavorite) }}
                {{ form_label(form.isFavorite, null, { 'label_attr': {'class': 'form-check-label'} }) }}

                <div class="form-error">{{ form_errors(form.isFavorite) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.price)}}
                {{ form_widget(form.price) }}
                <div class="form-error">{{ form_errors(form.price) }}</div>
            </div>
            <div class="form-group my-1">
               {{ form_row(form.ingredients, ) }}
                <div class="form-error">{{ form_errors(form.ingredients) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_row(form.submit) }}
            </div>

            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/pages/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cookable - Modifier une Recette{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-4">Modifier une Recette</h1>
        <div class="container mx-auto col-6">
            {{ form_start(form) }}
            <div class="form-group my-1">
                {{ form_label(form.name) }}
                {{ form_widget(form.name) }}
                <div class="form-error">{{ form_errors(form.name) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.time)}}
                {{ form_widget(form.time) }}
                <div class="form-error">{{ form_errors(form.time) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.people)}}
                {{ form_widget(form.people) }}
                <div class="form-error">{{ form_errors(form.people) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.difficulty) }}
                {{ form_widget(form.difficulty) }}
                <div class="form-error">{{ form_errors(form.difficulty) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.description) }}
                {{ form_widget(form.description) }}
                <div class="form-error">{{ form_errors(form.description) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_widget(form.isFavorite) }}
                {{ form_label(form.isFavorite, null, { 'label_attr': {'class': 'form-check-label'} }) }}

                <div class="form-error">{{ form_errors(form.isFavorite) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_label(form.price)}}
                {{ form_widget(form.price) }}
                <div class="form-error">{{ form_errors(form.price) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_row(form.ingredients, ) }}
                <div class="form-error">{{ form_errors(form.ingredients) }}</div>
            </div>
            <div class="form-group my-1">
                {{ form_row(form.submit) }}
            </div>

            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/pages/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cookable - Ingredients{% endblock %}


{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>Succès : </strong> {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('danger') %}
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>Erreur : </strong> {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('warning') %}
        <div class="alert alert-dismissible alert-warning">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>Attention : </strong> {{ message }}
        </div>
    {% endfor %}
    {% if  recettes|length > 0 %}
        <div class="container row text-center mx-auto">
            <h1 class="my-4">Mes Recettes</h1>
            <div class="container mx-auto col-12">
                <div class="count text-end d-flex flex-column my-2">
                    <small>Total : {{ recettes.getTotalItemCount }} recettes</small>
                    <a class="btn btn-primary my-1" href="{{ path('recettes.create') }}">Ajouter une recette</a>
                </div>
                <table class="table table-bordered table-hover table-striped text-end">
                    <thead class="thead-primary">
                    <tr class="table-primary">
                        <th class="px-3" scope="col" ><strong>#</strong></th>
                        <th class="px-3 text-start" scope="col" colspan="2">Recette</th>
                        <th class="px-3" scope="col" >Difficulté</th>
                        <th class="px-3" scope="col" >Prix €</th>
                        <th class="px-3" scope="col" >Favoris</th>
                        <th class="px-3" scope="col" colspan="2">Crée le</th>
                        <th class="px-3" scope="col" colspan="2">Modifiée le</th>
                        <th class="px-3" scope="col" colspan="2"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for recette in recettes %}
                        <tr>
                            <th class="px-3 align-middle" scope="row" >{{ "%02d"|format(recette.id) }}</th>
                            <td class="px-3 text-start align-middle" colspan="2">
                                <a href={{ path('recettes.show', {'id': recette.id})}}>
                                    {{ recette.name }}
                                </a>
                            </td>
                            <td class="px-3 align-middle" >
                                {{ recette.difficulty ? recette.difficulty~"/5":"n/a"}}
                            </td>
                            <td class="px-3 align-middle" >{{ recette.price ? recette.price~"€" : "n/a"}}</td>
                            <td class="px-3 align-middle" >{{ recette.favorite == 1 ? "✅" :"n/a" }}</td>
                            <td class="px-3 align-middle" colspan="2">{{ recette.createdAt|date("d-m-Y") }}</td>
                            <td class="px-3 align-middle" colspan="2">{{ recette.updatedAt|date("d-m-Y") }}</td>
                            <td class="d-flex align-items-center justify-content-evenly" colspan="2">
                                <a href="{{ path('recettes.edit', {'id': recette.id}) }}"
                                   class="btn-outline-primary btn"
                                   title="Modifier la recette"
                                >
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <button
                                        title="Supprimer la recette"
                                        type="button"
                                        class="btn-outline-danger btn"
                                        data-bs-toggle="modal" data-bs-target="#Modal{{ recette.id }}"
                                >
                                    <i class="fa-solid fa-trash-can"></i>
                                </button>
                                <div class="modal fade" id="Modal{{ recette.id }}" tabindex="-1"
                                     aria-labelledby="ModalLabel{{ recette.id }}" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="ModalLabel{{ recette.id }}">Attention
                                                                                                         !</h1>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body text-center">
                                                Voulez vous vraiment <strong class="text-danger">SUPPRIMER</strong>
                                                la recette suivante : <br> <br>
                                                "{{recette.name }}" ?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-primary"
                                                        data-bs-dismiss="modal">Annuler</button>
                                                <a  href="{{ path('recettes.delete', {'id': recette.id}) }}"
                                                    class="btn btn-danger">Supprimer</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="pagination mx-auto text-center">
                    {{ knp_pagination_render(recettes) }}
                </div>
            </div>
        </div>
    {% else %}
        <div class="container row text-center mt-4">
            <h4>Aucun élément à afficher</h4>
            <a href="/">← Retour à l'accueil</a>
        </div>
    {% endif %}
{% endblock %}

templates/pages/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cookable - Ingredients{% endblock %}


{% block body %}
    <div class="container mx-auto">
        {% if recette %}
            <h1 class="my-4">Recette n°{{ recette.id }}</h1>
            <div id="container" class="row mx-auto align-middle">
                <div class="col-6">
                    <h2>{{ recette.name }}</h2>
                    <p>{{ recette.time }} minutes</p>
                    <p>{{ recette.people }} personnes</p>
                    <p>{{ recette.difficulty }}/5</p>
                    <p>{{ recette.description }}</p>
                    <p>{{ recette.price }}€</p>
                    <p>{{ recette.favorite == 1 ? "✅" : "" }}</p>
                    <p>{{ recette.createdAt|date("d-m-Y") }}</p>
                    <p>{{ recette.updatedAt|date("d-m-Y") }}</p>
                </div>
            </div>
        {% else %}
            <h1 class="my-4">Recette non trouvée</h1>
        {% endif %}
    </div>
{% endblock %}